GroceryPoint/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using GroceryPoint.Dtos.Order;
using GroceryPoint.Dtos.Store;
using GroceryPoint.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace GroceryPoint.Controllers
{
    public class OrderController : StoreBaseController
    {
        private readonly IConfiguration _configuration;
        [Obsolete]
        private readonly IHostingEnvironment _appEnvironment;
        private string ApiGlobalUrl;

        [Obsolete]
        public OrderController(IConfiguration configuration, IHostingEnvironment appEnvironment)
        {
            _appEnvironment = appEnvironment;
            _configuration = configuration;
            ApiGlobalUrl = configuration.GetValue<string>("apiUrl");
        }
        public async Task<IActionResult> Index()
        {
            UserInfo user = new UserInfo();
            var result = HttpContext.Session.GetString("userSession");
            if (result != null)
            {
                user = JsonConvert.DeserializeObject<UserInfo>(HttpContext.Session.GetString("userSession"));
                var cityId = user.CityId;
            }

            string StorName = user.StoreName.Trim();
            ViewBag.StorName = StorName;

            string apiUrl = ApiGlobalUrl + "api/GetAllStoreOrders?storeID=" + user.storeId;
            List<StoreOrderDto> StoreOrderList = new List<StoreOrderDto>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(apiUrl))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    StoreOrderList = JsonConvert.DeserializeObject<List<StoreOrderDto>>(apiResponse);
                }
            }

            return View(StoreOrderList);
        }
        public async Task<IActionResult> OrderDetail(int? id)
        {
            ViewBag.Id = id;
            return View();
        }
        public async Task<IActionResult> OrderDetailView(int? id)
        {

            string apiUrl = ApiGlobalUrl + "api/GetStoreOrderDetails?orderID=" + id;

            StoreOrderDetailsDto storeOrderDetailsDtoObj = new StoreOrderDetailsDto();
            try
            {
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync(apiUrl))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        storeOrderDetailsDtoObj = JsonConvert.DeserializeObject<StoreOrderDetailsDto>(apiResponse);
                        ViewBag.OrderStatusId = new SelectList(await OrderStatusList(), "value", "label",
                            storeOrderDetailsDtoObj.StatusId);

                    }
                }
            }
            catch (Exception ex)
            {

                throw;
            }
            return PartialView("_OrderDetailViewPrtial",storeOrderDetailsDtoObj);
        }
        public async Task<List<OrderStatusDto>> OrderStatusList()
        {
            string apiUrl = ApiGlobalUrl + "api/GetAllOrderStatus";

            List<OrderStatusDto> OrderStatusDtoList = new List<OrderStatusDto>();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(apiUrl))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    OrderStatusDtoList = JsonConvert.DeserializeObject<List<OrderStatusDto>>(apiResponse);
                }
            }
            return OrderStatusDtoList;
        }
        public async Task<JsonResult> UpdateOrderStatus(int orderID, int orderStatusID)
        {
            string apiUrl = ApiGlobalUrl + "api/UpdateOrderStatus?orderID=" + orderID + "&orderStatusID=" + orderStatusID + "&userID=1";
            List<StoreOrderDto> ProductList = new List<StoreOrderDto>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(apiUrl))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    return Json(apiResponse);

                }
            }

            return Json(true);
        }
        public async Task<JsonResult> UpdateOrderItem(Int64? orderDetailsID, int qty)
        {
            UserInfo user = new UserInfo();
            var result = HttpContext.Session.GetString("userSession");
            if (result != null)
            {
                user = JsonConvert.DeserializeObject<UserInfo>(HttpContext.Session.GetString("userSession"));
            }
            else
            {
                user.UserId = 0;
            }

            string apiUrl = ApiGlobalUrl + "api/UpdateOrderItem?orderDetailsID=" + orderDetailsID + "&qty=" + qty + "&userID" + user.UserId;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync(apiUrl))
                {
                    //string StorName = Getuser.StoreName.Trim();
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    return Json(apiResponse);
                }
            }
        }
        public IActionResult CheckBox()
        {
            return View();
        }

    }
}

GroceryPoint/Controllers/StoresController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using GroceryPoint.Areas.Area.Controllers;
using GroceryPoint.Controllers;
using GroceryPoint.Dtos.Store;
using GroceryPoint.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using GroceryPoint.Global; 

namespace GroceryPoint.Area.Area.Controllers
{
    public class StoresController : Controller
    {
        private readonly IConfiguration _configuration;
        [Obsolete]
        private readonly IHostingEnvironment _appEnvironment;
        private string ApiGlobalUrl;

        public IActionResult dashboard()
        {
            return View();
        }
        [Obsolete]
        public StoresController(IConfiguration configuration, IHostingEnvironment appEnvironment)
        {
            _appEnvironment = appEnvironment;
            _configuration = configuration;
            ApiGlobalUrl = configuration.GetValue<string>("apiUrl");
        }
        public async Task<IActionResult> Selectstore()
        {
            var res = HttpContext.Session.GetString("userSession");
            UserInfo Getuser = new UserInfo();
            if (res != null)
            {
                Getuser = JsonConvert.DeserializeObject<UserInfo>(HttpContext.Session.GetString("userSession"));
                ViewBag.CityName = Getuser.CityName;

            }
            List<StoreSummaryDto> StoreSummaryDtoList = new List<StoreSummaryDto>();

            using (var httpClient = new HttpClient())
            {
                string apiUrl = ApiGlobalUrl + "api/GetAllStoresByCity?cityID=" + 1;
                using (var response = await httpClient.GetAsync(apiUrl))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    StoreSummaryDtoList = JsonConvert.DeserializeObject<List<StoreSummaryDto>>(apiResponse);
                }
            }
            return View(StoreSummaryDtoList);
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }
        public async Task<IActionResult> AddStore()
        {

            ViewBag.CityId = new SelectList(await CityList(), "CityId", "CityName");
            ViewBag.provinceID = new SelectList(await ProvinceList(), "provinceID", "provinceAbbr");

            return View();
        }
        public IActionResult Login()
        {
            var res = HttpContext.Session.GetString("userSession");
            if (res != null)
            {
                UserInfo user = JsonConvert.DeserializeObject<UserInfo>(HttpContext.Session.GetString("userSession"));
                ViewBag.CityName = user.CityName;
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(UserInfo userInfo)
        {

            UserInfo userInfoDetail = new UserInfo();
            userInfoDetail.UserName = userInfo.Email;
            userInfoDetail.Password = userInfo.Password;

            //UserInfo user = JsonConvert.DeserializeObject<UserInfo>(HttpContext.Session.GetString("userSession"));
            //userInfoDetail.UserId = 1;
            //userInfoDetail.UserName = userInfo.UserName;
            //userInfoDetail.Password = userInfo.Password;
            //userInfoDetail.CityId = user.CityId;
            string apiUrl = ApiGlobalUrl + "api/login?username=" + userInfoDetail.UserName + "&password=" + userInfoDetail.Password;

            using (var httpClient = new HttpClient())
            {


                using (var response = await httpClient.GetAsync(apiUrl))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    if (apiResponse == null || apiResponse == "")
                    {
                        ViewBag.error = "Failed to login";
                        return View();
                    }
                    else
                    {
                        apiResponse = await response.Content.ReadAsStringAsync();
                        UserInfo UserInfoAfterLogin = JsonConvert.DeserializeObject<UserInfo>(apiResponse);
                        try
                        {
                            var result = HttpContext.Session.GetString("userSession");
                            if (result != null)
                            {
                                UserInfo user = JsonConvert.DeserializeObject<UserInfo>(HttpContext.Session.GetString("userSession"));
                                var cityId = UserInfoAfterLogin.CityId;

                                user = JsonConvert.DeserializeObject<UserInfo>(apiResponse);
                                UserInfo userInfos = JsonConvert.DeserializeObject<UserInfo>(HttpContext.Session.GetString("userSession"));
                                user.CityId = cityId;
                                userInfo.UserTypeID = UserInfoAfterLogin.UserTypeID;
                                if (user.CityId == 0 || user.CityId == 0)
                                {
                                    user.CityId = UserInfoAfterLogin.CityId;
                                    user.CityName = UserInfoAfterLogin.CityName;
                                }
                                //user.UserTypeID = 2;
                                HttpContext.Session.SetString("userSession", JsonConvert.SerializeObject(user));


                                userInfoDetail = userInfos;
                                UserInfo.Current = user;
                                //user.UserTypeID = 2;
                                if (user.UserId != 0 && user.UserTypeID == 2)
                                {

                                    return RedirectToAction("dashboard", "stores");
                                }
                            }
                            else
                            {


                                UserInfo user = JsonConvert.DeserializeObject<UserInfo>(apiResponse);

                                HttpContext.Session.SetString("userSession", JsonConvert.SerializeObject(user));

                                UserInfoAfterLogin.CityId = 1;
                                userInfo.UserTypeID = UserInfoAfterLogin.UserTypeID;
                                userInfoDetail = user;
                                UserInfo.Current = user;
                                userInfoDetail.CityId = UserInfoAfterLogin.CityId;
                                userInfoDetail.CityName = UserInfoAfterLogin.CityName;
                                HttpContext.Session.SetString("userSession", JsonConvert.SerializeObject(userInfoDetail));
                                //user.UserTypeID = 2;

                                if (user.UserId != 0 && UserInfoAfterLogin.UserTypeID == 2)
                                {

                                    return RedirectToAction("dashboard", "stores");

                                }
                            }
                        }
                        catch (Exception ex)
                        {
                            ViewBag.error = "faild to login";
                            return View();
                        }

                    }
                }
            }

            return View();
        }
        [HttpPost]
        [Obsolete]
        public async Task<IActionResult> AddStore(StoreDto storeDto, IFormFile file)
        {
            string path_Root = _appEnvironment.WebRootPath;
            string filename = file.FileName;
            string filepath = path_Root + "//StoreImages";
            string FileNameForDb = Guid.NewGuid() + file.FileName;

            //if (!(Directory.Exists(path_Root + "//StoreImages//" + StorName)))
            //{
            //    Directory.CreateDirectory(path_Root + "//ProductImages//" + StorName);
            //}

            string saveImg = path_Root + "\\StoreImages\\" + FileNameForDb;
            using (var stream = new FileStream(saveImg, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }

            string apiUrl = ApiGlobalUrl + "api/AddStore?password=" + storeDto.password;

            StoreDto _storeDto = new StoreDto();
            _storeDto.storeName = storeDto.storeName;
            _storeDto.streetAddress = storeDto.streetAddress;
            _storeDto.unit = storeDto.unit;
            _storeDto.cityID = storeDto.cityID;
            _storeDto.provinceID = storeDto.provinceID;
            _storeDto.logo = FileNameForDb;
            _storeDto.phone = storeDto.phone;
            _storeDto.email = storeDto.email;
            _storeDto.postalCode = storeDto.postalCode;
            _storeDto.firstName = storeDto.firstName;
            _storeDto.lastName = storeDto.lastName;

            _storeDto.ipAddress = "1";



            using (var httpClient = new HttpClient())
            {
                var res = JsonConvert.SerializeObject(_storeDto);
                StringContent contentData = new StringContent(JsonConvert.SerializeObject(_storeDto), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync(apiUrl, contentData))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    if (apiResponse != null)
                    {
                        TempData["success"] = "Added Successfully";

                        return RedirectToAction("login", "stores");
                    }
                    //_productDto = JsonConvert.DeserializeObject<ProductUnitDto>(apiResponse);
                }
            }

GroceryPoint/Views/Stores/AddStore.cshtml
@model GroceryPoint.Dtos.Store.StoreDto

@{
    ViewData["Title"] = "Store Register";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

    <div class="row  justify-content-center align-items-center d-flex text-center h-100 white-box">
        <div class="col-md-11  h-50 ">
            <div class="text-light">
                <div class="logo box-logo">
                    <img class="text-center" src="~/UserTheme/images/new-grocerypoint-logo.png">
                </div>
            </div>
            <h3 class="slogn">
                Create an account to sell more
            </h3>
            <form asp-controller="Stores" asp-action="AddStore" class="add-store" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="rows">

                            <div class="form-group">
                                <input type="text" required max="100" name="storeName" placeholder="Store Name" class="form-control">
                            </div>
                            <div class="form-group">
                                <input type="text" required max="100" name="firstName" placeholder="First Name" class="form-control">
                            </div>
                            <div class="form-group">
                                <input type="text" required max="100" name="lastName" placeholder="Last Name" class="form-control">
                            </div>
                            <div class="form-group">
                                <input type="email" required max="100" name="email" placeholder="Email" class="form-control">
                            </div>

                            <div class="form-group">
                                <input type="password" required max="20" name="password" id="password" placeholder="Password (min 6 character)" class="form-control">
                            </div>
                            <div class="form-group">
                                <input type="password" required max="20" name="Reppassword" id="Reppassword" placeholder="Confirm Password" class="form-control">
                            </div>
                            <div class="form-group">
                                <input type="text" id="phone" max="10" required name="phone" placeholder="Phone" class="form-control">
                            </div>
                            <div class="form-group">
                                <input type="text" id="streetAddress" required name="streetAddress" placeholder="Street Address" class="form-control">
                            </div>
                            <div class="form-group">
                                <input type="text" id="unit" name="unit" placeholder="Unit" class="form-control">
                            </div>
                            <div class="form-group">
                                @Html.DropDownList("provinceID", ViewBag.provinceID as SelectList, "--Select  Province--", new { @required = "required", @class = "form-control search-slt" })

                                @*<input type="text" id="phone" name="Telephone" placeholder="Phone" class="form-control">*@
                            </div>
                            <div class="form-group">
                                @Html.DropDownList("CityId", new SelectList(""), "--Select City--", new { @class = "form-control" })


                                @*<input type="text" id="phone" name="Telephone" placeholder="Phone" class="form-control">*@
                            </div>

                            <div class="form-group">
                                <input type="text" id="postalCode" required name="postalCode" placeholder="Postal Code" class="form-control">
                            </div>


                            <div class="form-group image-upload">
                                <input type="file" name="file" class="form-control">
                            </div>
                            <div class="form-group">
                                <button class="btn btn-success btn-green" type="submit">Save</button>
                            </div>

                            @*<div class="form-group login-help">
                            <div class="or-box">
                                <span class="or">OR</span>
                                <div class="form-group">
                                    <button class="btn btn-success btn-green"><i class="fa fa-facebook-f"></i> &nbsp; facebook</button>
                                    <button class="btn btn-success btn-green"><i class="fa fa-google"></i> &nbsp; facebook</button>
                                </div>

                            </div>

                        </div>*@
                            <div class="login-help">
                                <p class="text-center">Already have an account? <a href="/accounts/login">Login</a></p>
                            </div>
                            <div class="login-help">
                                <p class="text-center">Forgot your password? <a href="#">Reset it</a></p>
                            </div>
                        </div>
                    </div>

                </div>
            </form>


        </div>
  
    </div>


@*<div class="register-form">
        <h2>Create an Account</h2>

        <form asp-action="Register" class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-field col-md-6">
                <label>First Name<span class="red">*</span></label>
                <input type="text" required name="FirstName">
                <span asp-validation-for="FirstName" class="text-danger"></span>

            </div>
            <div class="form-field col-md-6">
                <label>Last Name<span class="red">*</span></label>
                <input type="text" name="LastName" required>
                <span asp-validation-for="LastName" class="text-danger"></span>

            </div>
            <div class="form-field col-md-6">
                <label>Email Address<span class="red">*</span></label>
                <input type="text" name="UserName" required>
                <span asp-validation-for="UserName" class="text-danger"></span>

            </div>

            <div class="form-field col-md-6">
                <label>Telephone<span class="red">*</span></label>
                <input id="phone" type="text" name="Telephone" required>
                <span asp-validation-for="Telephone" class="text-danger"></span>

            </div>
            <div class="form-field col-md-6">
                <label>password<span class="red">*</span></label>
                <input id="phone" type="text" name="password" required>
                <span asp-validation-for="password" class="text-danger"></span>

            </div>
            <div class="form-field col-md-6">
            </div>
            <div class="form-field col-md-6">
                <label>Provinces <span class="red">*</span></label>
                @Html.DropDownList("provinceID", ViewBag.provinceID as SelectList, "-- Select Province--", new { @class = "form-control" })

                <span asp-validation-for="provinceID" class="text-danger"></span>

            </div>
            <div class="form-field col-md-6">
                <label>City<span class="red">*</span></label>
                @Html.DropDownList("CityId", new SelectList(""), "--Select City--", new { @class = "form-control" })

                <span asp-validation-for="CityId" class="text-danger"></span>

            </div>
            <div class="form-field col-md-12">
                <input type="submit" name="" value="Register" class="register-btn">
            </div>


        </form>

        <p class="para-txt">Already registeer with Grocery? <a href="/accounts/login">Login now</a></p>
    </div>*@
@section scripts{
}
<script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/3/jquery.inputmask.bundle.js"></script>
<script>
    $("#provinceID").change(function () {

        var Id = $(this).val();
        $.ajax({

            type: "Get",
            url: "/Accounts/GetCity?id=" + Id,
            contentType: "html",
            success: function (response) {
                $("#CityId").empty();
                $("#CityId").append(response);

            }

        })

    })
    $("#phone").inputmask({ "mask": "(999) 999-9999" });
</script>
<script>
    var password = document.getElementById("password")
        , confirm_password = document.getElementById("Reppassword");

    function validatepassword() {
        if (password.value != confirm_password.value) {
            confirm_password.setCustomValidity("passwords Don't Match");
        } else {
            confirm_password.setCustomValidity('');
        }
    }

    password.onchange = validatepassword;
    confirm_password.onkeyup = validatepassword;
</script>

GroceryPoint/Views/Stores/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

    <section id="configuration">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">
                            <a href="@Url.Action("Create", "Stores")" class="btn btn-info " style="font-size:18px">
                                Create New
                                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                            </a>

                        </h4>
                        <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                <li><a data-action="close"><i class="ft-x"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body card-dashboard">
                            <div class="table-responsive">


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

GroceryPoint/Views/Stores/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
    <section id="configuration">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">
                            <a href="@Url.Action("Create", "Stores")" class="btn btn-info " style="font-size:18px">
                              Back To List
                                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                            </a>

                        </h4>
                        <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                <li><a data-action="close"><i class="ft-x"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body card-dashboard">
                            <div class="table-responsive">


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

GroceryPoint/Views/Stores/dashboard.cshtml
@{
    ViewData["Title"] = "dashboard";
    Layout = "~/Views/Shared/_StoreLayout.cshtml";
}


<div class="row">
    <div class="col-md-12">
    <h2>Welcom to Your Store </h2>
    </div>
</div>

GroceryPoint/Views/Stores/order.cshtml
@model GroceryPoint.Dtos.Store.StoreOrderDetailsDto

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Grocery-Order</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicons -->
    <link href="img/favicon.png" rel="icon">
    <link href="img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,500,700,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,600,700&display=swap" rel="stylesheet">
    <!-- Bootstrap CSS File -->
    <link href="~/UserTheme/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <!-- Libraries CSS Files -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <style type="text/css">

        .bold {
            font-size: 16px;
            font-weight: 600;
        }

        .table {
            font-size: 14px;
        }

        h4 strong {
            font-size: 20px;
            color: #f80909;
        }
    </style>
</head>
<body>
    <p style="display:none" id="order_id">@ViewBag.Id</p>
    <div class="container" id="OderWithId">
       


    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script>
          var order_id = $("#order_id").text();    
        $("#OderWithId").load("/stores/orderView?id="+order_id)
       
    </script>


</body>
</html>